name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend-vite/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend-vite
        run: npm install

      - name: Lint frontend
        working-directory: frontend-vite
        run: npm run lint

      - name: Test frontend
        working-directory: frontend-vite
        run: npm run test

      - name: Build frontend
        working-directory: frontend-vite
        run: npm run build

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: backend
        run: pip install -r requirements.txt

      - name: Backend syntax check
        working-directory: backend
        run: python -m py_compile app/main.py

      - name: Run backend tests
        working-directory: backend
        run: pytest -q
